### PR TITLE
Further expansions, alternate expansions, possible corrections

### PR DESCRIPTION
**Pull request by LachlanAndrew**
I've made four change sets.  (This is my first pull request, so I'm not sure if it is requesting a pull of all of them.)

The aim of most of them is to allow a decomposition from a character all the way down to its component strokes.  To do this, I expand the radicals into smaller radicals (plus individual strokes as needed) and expand some (but not all) of the "unencoded DCs"

I have also made it more consistent in using the appropriate "component form" of the radicals (notably bamboo and gate).

Some existing expansions seem incorrect, and so the final change set proposes several changes.

### CODE REVIEW

**Comment by ekaunt** [comment]
i approve this message

**Comment by wmjordan** [comment]
About "expand radicals and other non-expanded characters" and "Expand unencoded DCs", I think your works are plausible. It is much better to use primitive radicals or individual strokes than those numeric annotations.

**Comment by hfhchan** [comment]
Although it is not noted in the README, this repository is the backing data used for IDS matching by the IRG.

A preliminary IDS check is conducted to characters added to a new working set.  The IDS matching is to catch possible duplicates to support IRG's unification work.

Hence, the algorithm needs to be fuzzy. There was never a need by this repository to distinguish between the "component form" and "full character" form. In fact, some of the IDS provided from other sources made these distinctions, but those distinctions are removed in this dataset.

Also, decomposing components to their individual strokes would drastically increase the resources needed for IDS matching, with little benefit to IRG work.

The pull request is not likely to be accepted due to the above reasons. I suggest forking the repository is probably better for your use-case.

**Comment by LachlanAndrew** [comment]
Thanks for your clear explanation.  Keep up the good work!

**Pull request closed without merging**
